from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    ld = LaunchDescription()

    # PCA board 1
    pcab_1_params = [
        {'i2c'         : 1     },  # I2C bus /dev/i2c-1
        {'slave_addr'  : 0x40  },  # PCA slave address
        {'freq'        : 50.0  },  # PWM frequency [Hz]
        {'angle_min'   : 0.0   },  # default servo config
        {'angle_max'   : 180.0 },  # ...
        {'pl_min'      : 0.4   },  # ...
        {'pl_max'      : 2.4   },  # ...
        # {'angle_min_0' : 0.0   },  # servo 0 config
        # {'angle_max_0' : 90.0  },  # ...
        # {'pl_min_0'    : 1.0   },  # ...
        # {'pl_max_0'    : 2.0   },  # ...
        # {'angle_min_1' : 0.0   },  # servo 1 config
        # {'angle_max_1' : 90.0  },  # ...
        # {'pl_min_1'    : 1.0   },  # ...
        # {'pl_max_1'    : 2.0   },  # ... and so on ...
        # {'angle_min_15': 0.0   },  # servo 15 config
        # {'angle_max_15': 90.0  },  # ...
        # {'pl_min_15'   : 1.0   },  # ...
        # {'pl_max_15'   : 2.0   },  # ...
    ]
    pcab_1 = Node(
        package='pca_board_bringup',
        executable='pca_board',
        parameters=pcab_1_params,
        namespace="/pcab_1",
    )
    ld.add_action(pcab_1)

    # # PCA board 2 ...
    # pcab_2_params = [
    #     {'i2c'         : 1     },  # I2C bus /dev/i2c-1
    #     {'slave_addr'  : 0x40  },  # PCA slave address
    #     {'freq'        : 50.0  },  # PWM frequency [Hz]
    #     {'angle_min'   : 0.0   },  # default servo config
    #     {'angle_max'   : 180.0 },  # ...
    #     {'pl_min'      : 0.4   },  # ...
    #     {'pl_max'      : 2.4   },  # ...
    #     # {'angle_min_0' : 0.0   },  # servo 0 config
    #     # {'angle_max_0' : 90.0  },  # ...
    #     # {'pl_min_0'    : 1.0   },  # ...
    #     # {'pl_max_0'    : 2.0   },  # ...
    #     # {'angle_min_1' : 0.0   },  # servo 1 config
    #     # {'angle_max_1' : 90.0  },  # ...
    #     # {'pl_min_1'    : 1.0   },  # ...
    #     # {'pl_max_1'    : 2.0   },  # ... and so on ...
    #     # {'angle_min_15': 0.0   },  # servo 15 config
    #     # {'angle_max_15': 90.0  },  # ...
    #     # {'pl_min_15'   : 1.0   },  # ...
    #     # {'pl_max_15'   : 2.0   },  # ...
    # ]
    # pcab_2 = Node(
    #     package='pca_board_bringup',
    #     executable='pca_board',
    #     parameters=pcab_2_params,
    #     namespace="/pcab_2",
    # )
    # ld.add_action(pcab_2)

    return ld
