from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    ld = LaunchDescription()

    # PCA board 1
    pcab_1_params = [
        {'i2c'         : 1     },  # I2C bus /dev/i2c-1
        {'slave_addr'  : 0x40  },  # PCA slave address
        {'freq'        : 50.0  },  # PWM frequency [Hz]

        {'angle_range' : 180.0 },  # default servo range
        {'pl_min'      : 0.4   },  # default min pulse len [ms]
        {'pl_max'      : 2.4   },  # default max pulse len [ms]
        {'zero_pos'    : 0.0   },  # default servo zero position
        {'angle_min'   : 0.0   },  # default servo min limit
        {'angle_max'   : 180.0 },  # default servo max limit

        # {'angle_range_0'  : 180.0 },  # servo 0 config, uncomment to
        # {'pl_min_0'       : 1.0   },  # override default parameters
        # {'pl_max_0'       : 2.0   },  # ...
        # {'zero_pos_0'     : 0.0   },  # ...
        # {'angle_min_0'    : 0.0   },  # ...
        # {'angle_max_0'    : 180.0 },  # ...

        # {'angle_range_1'  : 180.0 },  # servo 1 config
        # {'pl_min_1'       : 1.0   },  # ...
        # {'pl_max_1'       : 2.0   },  # ...
        # {'zero_pos_1'     : 0.0   },  # ...
        # {'angle_min_1'    : 0.0   },  # ...
        # {'angle_max_1'    : 180.0 },  # ...

        # {'angle_range_2'  : 180.0 },  # servo 2 config
        # {'pl_min_2'       : 1.0   },  # ...
        # {'pl_max_2'       : 2.0   },  # ...
        # {'zero_pos_2'     : 0.0   },  # ...
        # {'angle_min_2'    : 0.0   },  # ...
        # {'angle_max_2'    : 180.0 },  # ...

        # {'angle_range_3'  : 180.0 },  # servo 3 config
        # {'pl_min_3'       : 1.0   },  # ...
        # {'pl_max_3'       : 2.0   },  # ...
        # {'zero_pos_3'     : 0.0   },  # ...
        # {'angle_min_3'    : 0.0   },  # ...
        # {'angle_max_3'    : 180.0 },  # ...

        # {'angle_range_4'  : 180.0 },  # servo 4 config
        # {'pl_min_4'       : 1.0   },  # ...
        # {'pl_max_4'       : 2.0   },  # ...
        # {'zero_pos_4'     : 0.0   },  # ...
        # {'angle_min_4'    : 0.0   },  # ...
        # {'angle_max_4'    : 180.0 },  # ...

        # {'angle_range_5'  : 180.0 },  # servo 5 config
        # {'pl_min_5'       : 1.0   },  # ...
        # {'pl_max_5'       : 2.0   },  # ...
        # {'zero_pos_5'     : 0.0   },  # ...
        # {'angle_min_5'    : 0.0   },  # ...
        # {'angle_max_5'    : 180.0 },  # ...

        # {'angle_range_6'  : 180.0 },  # servo 6 config
        # {'pl_min_6'       : 1.0   },  # ...
        # {'pl_max_6'       : 2.0   },  # ...
        # {'zero_pos_6'     : 0.0   },  # ...
        # {'angle_min_6'    : 0.0   },  # ...
        # {'angle_max_6'    : 180.0 },  # ...

        # {'angle_range_7'  : 180.0 },  # servo 7 config
        # {'pl_min_7'       : 1.0   },  # ...
        # {'pl_max_7'       : 2.0   },  # ...
        # {'zero_pos_7'     : 0.0   },  # ...
        # {'angle_min_7'    : 0.0   },  # ...
        # {'angle_max_7'    : 180.0 },  # ...

        # {'angle_range_8'  : 180.0 },  # servo 8 config
        # {'pl_min_8'       : 1.0   },  # ...
        # {'pl_max_8'       : 2.0   },  # ...
        # {'zero_pos_8'     : 0.0   },  # ...
        # {'angle_min_8'    : 0.0   },  # ...
        # {'angle_max_8'    : 180.0 },  # ...

        # {'angle_range_9'  : 180.0 },  # servo 9 config
        # {'pl_min_9'       : 1.0   },  # ...
        # {'pl_max_9'       : 2.0   },  # ...
        # {'zero_pos_9'     : 0.0   },  # ...
        # {'angle_min_9'    : 0.0   },  # ...
        # {'angle_max_9'    : 180.0 },  # ...

        # {'angle_range_10' : 180.0 },  # servo 10 config
        # {'pl_min_10'      : 1.0   },  # ...
        # {'pl_max_10'      : 2.0   },  # ...
        # {'zero_pos_10'    : 0.0   },  # ...
        # {'angle_min_10'   : 0.0   },  # ...
        # {'angle_max_10'   : 180.0 },  # ...

        # {'angle_range_11' : 180.0 },  # servo 11 config
        # {'pl_min_11'      : 1.0   },  # ...
        # {'pl_max_11'      : 2.0   },  # ...
        # {'zero_pos_11'    : 0.0   },  # ...
        # {'angle_min_11'   : 0.0   },  # ...
        # {'angle_max_11'   : 180.0 },  # ...

        # {'angle_range_12' : 180.0 },  # servo 12 config
        # {'pl_min_12'      : 1.0   },  # ...
        # {'pl_max_12'      : 2.0   },  # ...
        # {'zero_pos_12'    : 0.0   },  # ...
        # {'angle_min_12'   : 0.0   },  # ...
        # {'angle_max_12'   : 180.0 },  # ...

        # {'angle_range_13' : 180.0 },  # servo 13 config
        # {'pl_min_13'      : 1.0   },  # ...
        # {'pl_max_13'      : 2.0   },  # ...
        # {'zero_pos_13'    : 0.0   },  # ...
        # {'angle_min_13'   : 0.0   },  # ...
        # {'angle_max_13'   : 180.0 },  # ...

        # {'angle_range_14' : 180.0 },  # servo 14 config
        # {'pl_min_14'      : 1.0   },  # ...
        # {'pl_max_14'      : 2.0   },  # ...
        # {'zero_pos_14'    : 0.0   },  # ...
        # {'angle_min_14'   : 0.0   },  # ...
        # {'angle_max_14'   : 180.0 },  # ...

        # {'angle_range_15' : 180.0 },  # servo 15 config
        # {'pl_min_15'      : 1.0   },  # ...
        # {'pl_max_15'      : 2.0   },  # ...
        # {'zero_pos_15'    : 0.0   },  # ...
        # {'angle_min_15'   : 0.0   },  # ...
        # {'angle_max_15'   : 180.0 }   # ...
    ]
    pcab_1 = Node(
        package='pca_board_bringup',
        executable='pca_board',
        parameters=pcab_1_params,
        namespace="/pcab_1",
    )
    ld.add_action(pcab_1)

    # # PCA board 2. Uncomment to add second board. Copy and change
    # # /pcab_<n> accordingly to add as many pca_board nodes as needed.
    # pcab_2_params = [
    #     {'i2c'         : 1     },  # I2C bus /dev/i2c-1
    #     {'slave_addr'  : 0x41  },  # PCA slave address
    #     {'freq'        : 50.0  },  # PWM frequency [Hz]

    #     {'angle_range' : 180.0 },  # default servo range
    #     {'pl_min'      : 0.4   },  # default min pulse len [ms]
    #     {'pl_max'      : 2.4   },  # default max pulse len [ms]
    #     {'zero_pos'    : 0.0   },  # default servo zero position
    #     {'angle_min'   : 0.0   },  # default servo min limit
    #     {'angle_max'   : 180.0 },  # default servo max limit

    #     # {'angle_range_0'  : 180.0 },  # servo 0 config
    #     # {'pl_min_0'       : 1.0   },  # ...
    #     # {'pl_max_0'       : 2.0   },  # ...
    #     # {'zero_pos_0'     : 0.0   },  # ...
    #     # {'angle_min_0'    : 0.0   },  # ...
    #     # {'angle_max_0'    : 180.0 },  # ...

    #     # {'angle_range_1'  : 180.0 },  # servo 1 config
    #     # {'pl_min_1'       : 1.0   },  # ...
    #     # {'pl_max_1'       : 2.0   },  # ...
    #     # {'zero_pos_1'     : 0.0   },  # ...
    #     # {'angle_min_1'    : 0.0   },  # ...
    #     # {'angle_max_1'    : 180.0 },  # ...

    #     # {'angle_range_2'  : 180.0 },  # servo 2 config
    #     # {'pl_min_2'       : 1.0   },  # ...
    #     # {'pl_max_2'       : 2.0   },  # ...
    #     # {'zero_pos_2'     : 0.0   },  # ...
    #     # {'angle_min_2'    : 0.0   },  # ...
    #     # {'angle_max_2'    : 180.0 },  # ...

    #     # {'angle_range_3'  : 180.0 },  # servo 3 config
    #     # {'pl_min_3'       : 1.0   },  # ...
    #     # {'pl_max_3'       : 2.0   },  # ...
    #     # {'zero_pos_3'     : 0.0   },  # ...
    #     # {'angle_min_3'    : 0.0   },  # ...
    #     # {'angle_max_3'    : 180.0 },  # ...

    #     # {'angle_range_4'  : 180.0 },  # servo 4 config
    #     # {'pl_min_4'       : 1.0   },  # ...
    #     # {'pl_max_4'       : 2.0   },  # ...
    #     # {'zero_pos_4'     : 0.0   },  # ...
    #     # {'angle_min_4'    : 0.0   },  # ...
    #     # {'angle_max_4'    : 180.0 },  # ...

    #     # {'angle_range_5'  : 180.0 },  # servo 5 config
    #     # {'pl_min_5'       : 1.0   },  # ...
    #     # {'pl_max_5'       : 2.0   },  # ...
    #     # {'zero_pos_5'     : 0.0   },  # ...
    #     # {'angle_min_5'    : 0.0   },  # ...
    #     # {'angle_max_5'    : 180.0 },  # ...

    #     # {'angle_range_6'  : 180.0 },  # servo 6 config
    #     # {'pl_min_6'       : 1.0   },  # ...
    #     # {'pl_max_6'       : 2.0   },  # ...
    #     # {'zero_pos_6'     : 0.0   },  # ...
    #     # {'angle_min_6'    : 0.0   },  # ...
    #     # {'angle_max_6'    : 180.0 },  # ...

    #     # {'angle_range_7'  : 180.0 },  # servo 7 config
    #     # {'pl_min_7'       : 1.0   },  # ...
    #     # {'pl_max_7'       : 2.0   },  # ...
    #     # {'zero_pos_7'     : 0.0   },  # ...
    #     # {'angle_min_7'    : 0.0   },  # ...
    #     # {'angle_max_7'    : 180.0 },  # ...

    #     # {'angle_range_8'  : 180.0 },  # servo 8 config
    #     # {'pl_min_8'       : 1.0   },  # ...
    #     # {'pl_max_8'       : 2.0   },  # ...
    #     # {'zero_pos_8'     : 0.0   },  # ...
    #     # {'angle_min_8'    : 0.0   },  # ...
    #     # {'angle_max_8'    : 180.0 },  # ...

    #     # {'angle_range_9'  : 180.0 },  # servo 9 config
    #     # {'pl_min_9'       : 1.0   },  # ...
    #     # {'pl_max_9'       : 2.0   },  # ...
    #     # {'zero_pos_9'     : 0.0   },  # ...
    #     # {'angle_min_9'    : 0.0   },  # ...
    #     # {'angle_max_9'    : 180.0 },  # ...

    #     # {'angle_range_10' : 180.0 },  # servo 10 config
    #     # {'pl_min_10'      : 1.0   },  # ...
    #     # {'pl_max_10'      : 2.0   },  # ...
    #     # {'zero_pos_10'    : 0.0   },  # ...
    #     # {'angle_min_10'   : 0.0   },  # ...
    #     # {'angle_max_10'   : 180.0 },  # ...

    #     # {'angle_range_11' : 180.0 },  # servo 11 config
    #     # {'pl_min_11'      : 1.0   },  # ...
    #     # {'pl_max_11'      : 2.0   },  # ...
    #     # {'zero_pos_11'    : 0.0   },  # ...
    #     # {'angle_min_11'   : 0.0   },  # ...
    #     # {'angle_max_11'   : 180.0 },  # ...

    #     # {'angle_range_12' : 180.0 },  # servo 12 config
    #     # {'pl_min_12'      : 1.0   },  # ...
    #     # {'pl_max_12'      : 2.0   },  # ...
    #     # {'zero_pos_12'    : 0.0   },  # ...
    #     # {'angle_min_12'   : 0.0   },  # ...
    #     # {'angle_max_12'   : 180.0 },  # ...

    #     # {'angle_range_13' : 180.0 },  # servo 13 config
    #     # {'pl_min_13'      : 1.0   },  # ...
    #     # {'pl_max_13'      : 2.0   },  # ...
    #     # {'zero_pos_13'    : 0.0   },  # ...
    #     # {'angle_min_13'   : 0.0   },  # ...
    #     # {'angle_max_13'   : 180.0 },  # ...

    #     # {'angle_range_14' : 180.0 },  # servo 14 config
    #     # {'pl_min_14'      : 1.0   },  # ...
    #     # {'pl_max_14'      : 2.0   },  # ...
    #     # {'zero_pos_14'    : 0.0   },  # ...
    #     # {'angle_min_14'   : 0.0   },  # ...
    #     # {'angle_max_14'   : 180.0 },  # ...

    #     # {'angle_range_15' : 180.0 },  # servo 15 config
    #     # {'pl_min_15'      : 1.0   },  # ...
    #     # {'pl_max_15'      : 2.0   },  # ...
    #     # {'zero_pos_15'    : 0.0   },  # ...
    #     # {'angle_min_15'   : 0.0   },  # ...
    #     # {'angle_max_15'   : 180.0 }   # ...
    # ]
    # pcab_2 = Node(
    #     package='pca_board_bringup',
    #     executable='pca_board',
    #     parameters=pcab_2_params,
    #     namespace="/pcab_2",
    # )
    # ld.add_action(pcab_2)

    return ld
